name: FTP Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, zip, bcmath
          tools: composer
      - name: Set working directory
        run: cd /path/to/your/laravel/project  # Set the correct directory where artisan exists
      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader
      - name: Set up .env
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate
      - name: Prepare Laravel application
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
      - name: Set permissions
        run: |
          chmod -R 775 storage bootstrap/cache
          mkdir -p storage/logs
          chmod -R 775 storage/logs
      - name: Exclude files
        run: |
          echo "node_modules/" >> .gitignore
          echo "storage/framework/cache/" >> .gitignore
          echo "storage/framework/sessions/" >> .gitignore
          echo "vendor/" >> .gitignore
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /
          exclude: |
            .git*
            node_modules
            storage/logs
            vendor
